// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjpfoguzwsoweehfzmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqcGZvZ3V6d3Nvd2VlaGZ6bXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTY2OTksImV4cCI6MjA2NTU3MjY5OX0.fjKN4LOgLmbCqzXhiO_zJ7uuSA-Ed0RHS1llnmms3O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);